### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [1]:
import numpy as np
np.__version__

'1.24.3'

In [8]:
list_data = ['강아지', '원숭이', '꽃', '45', '100']
array_data = np.array(list_data)

In [12]:
print(array_data.ndim) #차원
print(array_data.size) #요소 수
print(array_data.dtype) # 데이터 형
print(array_data.shape) # 전체 구조

1
5
<U3
(5,)


#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
array_list = np.ones((2, 3)) #2행, 3열
print(array_list)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [19]:
array_1 = np.arange(51, 81) #51-80까지 1차원 배열 생성
array_2 = np.reshape(array_1, (6, 5)) # 5행 6열 2차원 배열로 변형
print(array_2) # 출력

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]
 [76 77 78 79 80]]


#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [21]:
array_2 = np.arange(51, 81).reshape(6, 5)
array_2 = array_2.astype(np.float64) # 배열 자료형을 float64로 변환
print(array_2)
print(array_2.dtype) #dtype으로 변환된 배열의 자료형 출력

[[51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60.]
 [61. 62. 63. 64. 65.]
 [66. 67. 68. 69. 70.]
 [71. 72. 73. 74. 75.]
 [76. 77. 78. 79. 80.]]
float64


#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [34]:
array_2d = np.array([[ 1,  4,  5,  6],
                    [56, 23, 45, 67],
                    [ 8,  4,  6, 10]]) #  어레이 2d 정의 2차원
array_1d = array_2d.reshape(-1) # 어레이 2d 차원 축소 -> 어레이 1
print(array_1d) # 어레이 1 확인
sliced_array = array_1d[5:10] # 어레이 슬라이싱
print(sliced_array) #어레이 슬라이싱 출력

[ 1  4  5  6 56 23 45 67  8  4  6 10]
[23 45 67  8  4]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [35]:
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_1d[0], array_1d[-3:] = array_1d[-1], array_1d[:3]  
# array_1d[0]: 배열의 첫 번째 요소, array_1d[-3:]: 배열의 마지막 세 개의 요소, array_1d[:3]: 배열의 처음 세 개의 요소
print(array_1d)

[10  2  3  4  5  6  7 10  2  3]


#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [37]:
array_2d = np.random.randint(10, 100, (5, 5)) # array_2d 랜덤  , randint 함수의 첫 번째 인수는 최솟값 (포함), 두 번째 인수는 최댓값 (미포함)입니다.
print(array_2d)

[[89 30 20 39 94]
 [52 65 22 69 69]
 [19 24 39 62 32]
 [66 22 53 42 68]
 [96 78 14 44 86]]


#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [38]:
numbers = np.random.randint(1, 101, 7) # 랜덤 1 - 100, 7 개
max_v = np.max(numbers) # 최댓값
min_v = np.min(numbers) # 최솟값

print(numbers)
print(max_v)
print(min_v)

[74  7  9 89 54 33 73]
89
7


#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [40]:
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array_2 = np.array([[11, 12, 13],
                    [14, 15, 16],
                    [17, 18, 19]])
array_3 = np.array([[21, 22, 23],
                    [24, 25, 26],
                    [27, 28, 29]])

result_1 = np.concatenate((array_1, array_2, array_3), axis=1) # np.concatenate((array_1, array_2, array_3), axis=1): axis=1 옵션을 사용하여 세 개의 배열을 열 방향으로 합칩니다.
print(result_1)

result_2 = np.concatenate((array_1, array_2, array_3), axis=0)
print(result_2) # np.concatenate((array_1, array_2, array_3), axis=0): axis=0 옵션을 사용하여 세 개의 배열을 행 방향으로 합칩니다.

[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [47]:
arr = np.random.choice(100, 40, replace=False)
filtered_arr = arr[arr>50]
print(f"before:\n{arr}")
print(f"after:\n{filtered_arr}")

before:
[10 17 33  2 83 27 50 69 67 52 55 61 72 96  4 43 22 92 99 47 41 12 38 71
 14  5 49 84 15 77 86 78 13 46 82 91 68 16 30 35]
after:
[83 69 67 52 55 61 72 96 92 99 71 84 77 86 78 82 91 68]


#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [56]:
#1번
kor = np.array( [60,55,70,30,20,90])
max_score = np.max(kor)
print("1", max_score)

#2
high_scores = kor[kor >= 80]
print("2", high_scores)

#3
mid_scores = kor[(kor >= 50) & (kor <= 80)]
print("3", mid_scores)

#4
average_score = np.mean(kor)
print("4", average_score)

#5
total_score = np.sum(kor)
print("5", total_score)

#6
kor_40 = kor[kor > 40]
print(kor_40)

#7
high_score_idx = kor >= 50
kor[high_score_idx] = (kor[high_score_idx] * 1.1).astype(np.int32)  # 계산 후 데이터 형변환
print(kor)

#8
top_3_idx = np.argsort(kor)[-3:]

print(f"국어 점수 상위 3명: {kor[top_3_idx]}")

#9
result = ["합격" if score >= 70 else "불합격" for score in kor]

# 결과 출력
for score, result in zip(kor, result):
    print(f"{score} {result}")

1 90
2 [90]
3 [60 55 70]
4 54.166666666666664
5 325
[60 55 70 90]
[66 60 77 30 20 99]
국어 점수 상위 3명: [66 77 99]
66 불합격
60 불합격
77 합격
30 불합격
20 불합격
99 합격
